llm:
  - 
    name: chatglm_default
    type: chatglm4
    path: /Users/bytedance/workspace/rina2b
    api_key: your_api_key
  - 
    name: chatglm4
    type: chatglm4
    api_key: your_api_key
memory:
  - name: memory_default
    longterm:
      type: vector
      path: /Users/bytedance/workspace/rina3b/memory/longterm
    shotterm:
      limit: 50
agent:
  - 
    name: default
    persona: lite
    llm: chatglm_default
    memory: memory_default
    tools:
      - search_web
rina:
  persona: rina
  llm: chatglm4
  memory: memory_default