llm:
  - 
    name: chatglm_default
    type: chatglm3
    path: /Users/bytedance/workspace/rina2b
  - 
    name: chatglm4
    type: chatglm4
    api_key: your_api_key
memory:
  - name: memory_default
    longterm:
      type: vector
      path: /Users/bytedance/workspace/rina2b/memory/longterm
    shotterm:
      limit: 50
agent:
  - name: default
    llm: chatglm_default
    memory: memory_default
    tools:
      - search_web
rina:
  agent: default